# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdevtests',
                'doc_host': 'https://gmjen.github.io',
                'git_url': 'https://github.com/gmjen/nbdevtests',
                'lib_path': 'nbdevtests'},
  'syms': {'nbdevtests.core': {'nbdevtests.core.foo': ('core.html#foo', 'nbdevtests/core.py')}}}
